### ISSUE TITLE
Could use with refactor installation guide 

### ISSUE THREAD

**Issue by stephyswe** [clerkinc/t3-turbo-and-clerk#22]
An easier way to write what the user needs to do to start this t3-clerk app from repo, would be useful.

Attempt to start Next13 app.
#### Clone project repo
git clone https://github.com/clerkinc/t3-turbo-and-clerk.git
#### Install project
* pnpm i
#### Rename to .env file and add api keys from clerk.dev's dashboard.
* cp .env.example .env 
- Add env variables. 
- visit and login to https://clerk.dev/ - dashboard - api keys. 
- NEXT_PUBLIC_CLERK_FRONTEND_API=pk_test_cm...
- CLERK_API_KEY=sk_test_vB...
#### Push the Prisma schema to your database
pnpm db-push
#### start dev instance
pnpm dev

### Missing instructions 
1. Instruction to stop port. Command "pnpm dev" runs on localhost:3000 and when close down, and open again 3000 is still occupied and 3001 is used. An easier way to show how to kill first port (3000) would be nice. 
←[33m@acme/expo:dev: ←[0mStarting project at D:\Dev\code-t3\t3-turbo-and-clerk\apps\expo
←[34m@acme/nextjs:dev: ←[0mwarn  - Port 3000 is in use, trying 3001 instead.
←[34m@acme/nextjs:dev: ←[0mwarn  - Port 3001 is in use, trying 3002 instead.
←[34m@acme/nextjs:dev: ←[0mwarn  - Port 3002 is in use, trying 3003 instead.
←[34m@acme/nextjs:dev: ←[0mwarn  - Port 3003 is in use, trying 3004 instead.
←[34m@acme/nextjs:dev: ←[0mwarn  - Port 3004 is in use, trying 3005 instead.
2. Instruction to start next13. "Command "pnpm dev" runs on localhost:3000. When open browser on localhost:3000 error is shown - 
-- https://pk_test_cm9.../npm/@clerk/clerk-js@latest/dist/clerk.browser.js net::ERR_NAME_NOT_RESOLVED. Im pretty sure my env files are wrong, could love some help what to write there.

**Comment by perkinsjr** [comment]
This is indeed because we just released brand new way to work with Clerk and I haven't had time to update this open source project.

Your .env should now be:

NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=publishable_key
CLERK_SECRET_KEY=clerk_secret

and in your expo project 

<ClerkProvider publishableKey={"your_publishable_key'}

This should get you up and running. 

In regards to 

`Instruction to stop port. Command "pnpm dev" runs on localhost:3000 and when close down, and open again 3000 is still occupied and 3001 is used. An easier way to show how to kill first port (3000) would be nice.`

You should be able to shut it down just like any other application, e.g `control + c` on Macbooks for example.

**Comment by perkinsjr** [comment]
Just noticed a bug in our expo SDK so I need that fix in place for Expo to work but the next.js side is unaffected.
