### ISSUE TITLE
Google Auth not working

### ISSUE THREAD

**Issue by neilk17** [clerkinc/t3-turbo-and-clerk#66]
For some reason google auth doesn't work in Testflight though it works in dev / localhost and on nextjs production instance.

What I have tried so far 
- Updated redirecgt url on clerk dashboard
- Added scheme 
- Checked information on google cloud dashboard 

Would really appreciate any help, I have searched through everything available in the docs.

**Comment by perkinsjr** [comment]
Need more information please fill out this:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Logs**
Please provide logs showing the error.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by neilk17** [comment]
Thanks James, I figured out the issue. 

In the documentation this

your-app-scheme://oauth-native-callback

should be 

your-app-scheme://oauth_callback
